# Generated by Django 4.2.9 on 2025-05-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
